build.channel=${embedded.build.channel}
mcprotocollib.dependency.version=${mcprotocollib.version}
mcprotocollib.resolved.version=${mcprotocollib.resolved-version}
mcprotocollib.sha256=${mcprotocollib.sha256}
viaversion.dependency.version=${viaversion.runtime.dependency-version}
viaversion.resolved.version=${viaversion.runtime.version}
viaversion.url=${viaversion.runtime.url}
viaversion.sha256=${viaversion.runtime.sha256}
